-- WAREHOUSE DATABASE SCHEMA DESIGN --
CREATE DATABASE warehouse;
USE warehouse;

CREATE TABLE CITIES (
    CITY CHAR(20) PRIMARY KEY,
    STATE CHAR(20),
    ZIP INT(6)
);  

CREATE TABLE WAREHOUSES (
  WID INT PRIMARY KEY,
  WNAME CHAR(30),
  LOCATION CHAR(20),
  EXTRA_CONTEXT JSON,
  FOREIGN KEY (LOCATION) REFERENCES CITIES(CITY)
);

CREATE TABLE STORES (
    SID INTEGER PRIMARY KEY,
    STORE_NAME CHAR(20),
    LOCATION_CITY CHAR(20),
    WAREHOUSE INT,
    FOREIGN KEY (LOCATION_CITY)
        REFERENCES CITIES (CITY),
    FOREIGN KEY (WAREHOUSE)
        REFERENCES WAREHOUSES (WID)
);

CREATE TABLE CUSTOMER (
    CNO INTEGER PRIMARY KEY,
    CNAME CHAR(50),
    ADDR VARCHAR(50),
    CU_CITY CHAR(20),
    FOREIGN KEY (CU_CITY)
        REFERENCES CITIES (CITY)
);

CREATE TABLE ORDERS (
    ONO INTEGER PRIMARY KEY,
    ODATE DATE,
    CNO INTEGER,
    FOREIGN KEY (CNO)
        REFERENCES CUSTOMER (CNO)
);

CREATE TABLE ITEMS (
    ITEMNO INTEGER PRIMARY KEY,
    DESCRIPTION TEXT,
    WEIGHT DECIMAL(5 , 2 ),
    COST DECIMAL(5 , 2 )
);

CREATE TABLE ITEMS_ORDERS (
    ITEMNO INTEGER,
    ONO INTEGER,
    ORDERED_QUANTITY INTEGER,
    FOREIGN KEY (ITEMNO)
        REFERENCES ITEMS (ITEMNO),
    FOREIGN KEY (ONO)
        REFERENCES ORDERS (ONO)
);

CREATE TABLE STORES_ITEMS (
    SID INTEGER,
    ITEMNO INTEGER,
    QUANTITY INTEGER,
    FOREIGN KEY (SID)
        REFERENCES STORES (SID),
    FOREIGN KEY (ITEMNO)
        REFERENCES ITEMS (ITEMNO)
);

SHOW TABLES; 